### PR TITLE
set header size on reflow

### PR DESCRIPTION
**Pull request by ameily**
I am seeing an issue where I'm calling `floatThead('reflow')`, which is causing a `<th>` in the header to wrap and resize. After this, the first row of the `<tbody>` is cut off. I've made a jsfiddle that matches what I'm doing locally but I cannot reproduce there. It happens occasionally on a project I'm working on locally.

The fix appears to be pretty straightforward: change the call to `repositionFloatContainer` for reflow events to also set the header height.

- OS: Windows 10
- Browser: Chrome 63 and Firefox 57
- jsFiddle: https://jsfiddle.net/ry7dv6wj/2/
- floatThread Version: 2.0.3

### CODE REVIEW

**Comment by mkoryak** [comment]
Looks ok to me. You didn't generate dist, so it won't be in the minified version until I cut the next release or someone else submits a PR with it

**Comment by ameily** [comment]
I built the dist versions. I had to use the `uglify-js` package because `ulgifyjs` has been deprecated.

**Comment by mkoryak** [comment]
Do you mind also updating package.json deps as well?

**Comment by ameily** [comment]
Done.

**Comment by mkoryak** [comment]
Thanks!

**Pull request merged**
