### PR TITLE
potential fix for #333

### PR DESCRIPTION
**Pull request by timbowhite**

### CODE REVIEW

**Comment by mkoryak** [comment]
I havent forgotten, but spare time is lacking right now.

**Comment by barryvdh** [comment]
This does give me a more stable scrolling experience, but it doesn't seem to calculate to bottom of the table correctly. The original version scrolls out of frame, but you version keeps visible untill the next thead.

**Comment by fredyfx** [comment]
Hi there, I arrived by miracle on this library. Thanks! I am testing it. The little bouncing/shaking effect when scrolling using the mouse wheel still there. I'm using Microsoft Edge. Something interesting here: when I use the scroll bar instead of the mouse wheel, there is no bouncing/shaking effect.

**Comment by mkoryak** [comment]
I will really look at this soon!

**Comment by mkoryak** [comment]
I keep lying, I really do intend to this in the next 2 years. The only open source I contribute to these days involves kids and houses.

**Comment by timbowhite** [comment]
No problem. AFAIK, the changes have been working well in production on tld-list.com since last Feb.

**Comment by mkoryak** [comment]
sorry, this PR isn't going to happen.

**Pull request closed without merging**
