### PR TITLE
Keyboard focus order

### PR DESCRIPTION
**Pull request by robinpoort**
Info can be found here: #230 

Updated Fiddle with absolute position, fixed position and inner scrolling examples. These are the three changes made. http://jsfiddle.net/fqo2k6zz/2/

### CODE REVIEW

**Comment by mkoryak** [comment]
Now I'm on holiday :)
Ill look at this once I get back

**Comment by mkoryak** [comment]
looks good, nice fiddle too :)

**Comment by robinpoort** [comment]
:+1:

**Comment by mkoryak** [comment]
your patch was released in 1.3 along with some breaking changes.

**Comment by robinpoort** [comment]
:+1:

**Pull request merged**
