### PR TITLE
TypeScript definitions

### PR DESCRIPTION
**Pull request by jmariller**
Added `.d.ts` file and adjusted `package.json` with respective reference.

### CODE REVIEW

**Comment by mkoryak** [comment]
Thanks

**Comment by mkoryak** [comment]
Do you need me to cut a new release with this stuff?

**Comment by jmariller** [comment]
My pleasure! And yes, I think it would be good to have a new release - probably a minor one is enough.

**Comment by jmariller** [comment]
@mkoryak I confirm a new release is needed, as I tried to uninstall/re-install the library through npm and it seems it does not reflect the latest changes.

**Comment by mkoryak** [comment]
I'll cut one tomorrow after the US holiday :)

**Comment by jmariller** [comment]
No worries, thanks a lot! Enjoy the holiday :)

**Pull request merged**
