### PR TITLE
Possible fix for Issue#300 : Reflow When Table is Horizontally Scrolled.

### PR DESCRIPTION
**Pull request by rshah88**
Cache the scrollLeft value on floatContainer before reflow() and set it back on the floatContianer at end of reflow().

### CODE REVIEW

**Comment by mkoryak** [comment]
Sorry, this wont do. 

First, the file that you should be editing should be `/jquery.floatThead.js` (not in /dist)

second, I cannot get a diff via github because it looks like your commit is double spaced. Please try to match the style of the original. 

You can commit your fixes to this fork and this PR will be updated.

**Comment by rshah88** [comment]
Sorry about that, have committed the correct file and also cleaned the line endings. Let me know.

**Comment by rshah88** [comment]
Also would like to know on how soon can you have a release with this fix ? Thanks.

**Comment by mkoryak** [comment]
you are still making a change to a file in /dist

can you modify the one at the project root. 
Otherwise it looks good. I can release a patch version after I do a few tests and it checks out. Probably tomorrow at the latest (after you make the change above)

**Comment by rshah88** [comment]
Sounds good. Let me know so I can get the latest.

**Pull request merged**
