### PR TITLE
Added CSS transform to boost performance on retina display's.

### PR DESCRIPTION
**Pull request by arjanc**
Added css transform which boosts performance on retina display's. CSS transform uses the GPU for calculations. Changing the top/left position on a absolute element is done by the CPU.

Added grunt package with version number to build the project even when you have a newer grunt version installed.

### CODE REVIEW

**Comment by mkoryak** [comment]
I'll test this tomorrow. Please add vendor prefixes also since this plugin supports ie9 and older browsers

**Comment by arjanc** [comment]
I've added vendor prefixes and a IE8 check. IE8 doesn't support css transform property.

**Comment by mkoryak** [comment]
sorry, ive been busy with life stuff. Ill get to this soon

**Comment by mkoryak** [comment]
ok, so I finally checked this out (sorry it took so long). there is an issue - with fractional pixel translate there is blurring. Take a look at these screen shots:

your pr:
screen shot 2016-09-07 at 5 14 24 pm

current code:
screen shot 2016-09-07 at 5 14 29 pm

**Comment by mkoryak** [comment]
you can reproduce this every time with this temp change:

```js
if (pos.top) {
    pos.top = pos.top + .5;
    transform += 'translateY(' + pos.top + 'px)';
}
```

I did some research on this, and there seem to be a [few](http://stackoverflow.com/questions/15464055/css-transition-effect-makes-image-blurry-moves-image-1px-in-chrome) [different](http://stackoverflow.com/questions/31109299/css-transform-translate-50-50-makes-texts-blurry) [solutions](http://browser.colla.me/show/css_transformation_scale_cause_blurring) but none of them are cross browser - or maybe I havent looked hard enough. 

This is a deal breaker for me as it stands, though If you can figure out a way to prevent the blurring in the major browsers (chrome, firefox and ie11+) we can put this feature behind an opt in flag. 

on a side note, this plugin does not support IE8, so the check in your code is not needed

**Comment by mkoryak** [comment]
actually, what I should do is fall back on the setting top/left if fractional pixel position is needed, otherwise use your method - at least until you find a solution for the blurring

**Comment by arjanc** [comment]
To me this looks more like a fractional transform issue (half pixels).
If you feed the browser with a fractional offset, like 0.5 instead of 1, text will look blurry. Firefox and Chrome calculates pixels different.

My solution would be to round the positions.

`
pos.top = Math.round(pos.top);
pos.left = Math.round(pos.left);
`

**Comment by mkoryak** [comment]
I will try it after I can reproduce this again without that hack and round them to see if it looks right.

I am weary of that solution because I have to support fractional pixel column widths in order for them to line up correctly, though it is more noticeable there because of compound error.

For example this might be an issue if the rounding makes it so that the header floats over a 1px border and covers it up.

**Comment by mkoryak** [comment]
ok, rounding appears to work. its merged finally :)

**Comment by arjanc** [comment]
Great!

I am happy i could contribute.

**Comment by mkoryak** [comment]
this is now released as 1.4.4

**Comment by icemall** [comment]
Thanks for the great plugin! But I'm using version 2.4.4 and blurriness is an issue if browser zoom differs from 100%. I'm using Chrome.

100%
image

110%
image

90%
image

**Pull request merged**
